build:
  maxIssues: 0

config:
  validation: true

processors:
  active: true

console-reports:
  active: true

comments:
  active: false

complexity:
  LongMethod:
    active: true
    threshold: 60

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 120

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable
